# Generated by Django 3.2 on 2023-04-01 20:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('derivadospetroleo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumoderivadospetroleo',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
