# Generated by Django 3.2 on 2023-04-04 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('derivadospetroleo', '0003_alter_consumoderivadospetroleo_fecha_registro'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAceite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
            ],
        ),
        migrations.CreateModel(
            name='TipoRefrigerante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Refrigerante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('cantidad_galones', models.FloatField(default=0)),
                ('id_tipo_refrigerante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='derivadospetroleo.tiporefrigerante')),
            ],
        ),
        migrations.CreateModel(
            name='Aceite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('cantidad_galones', models.FloatField(default=0)),
                ('id_tipo_aceite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='derivadospetroleo.tipoaceite')),
            ],
        ),
    ]
