# Generated by Django 3.2 on 2023-04-04 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('derivadospetroleo', '0004_aceite_refrigerante_tipoaceite_tiporefrigerante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aceite',
            name='fecha_registro',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='consumoderivadospetroleo',
            name='fecha_registro',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='refrigerante',
            name='fecha_registro',
            field=models.DateField(),
        ),
    ]
