# Generated by Django 3.2 on 2023-04-01 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('combustible', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquiposViaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Viajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.FloatField()),
                ('id_equipos_viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajes.equiposviaje')),
                ('id_tipo_emision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='combustible.tipoemision')),
            ],
        ),
    ]
