# Generated by Django 3.2 on 2023-04-04 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0002_alter_viajes_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viajes',
            name='fecha_registro',
            field=models.DateField(),
        ),
    ]
