# Generated by Django 3.2 on 2023-04-01 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaConsumoCombustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre')),
            ],
        ),
        migrations.CreateModel(
            name='TipoEmision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre')),
            ],
        ),
        migrations.CreateModel(
            name='ConsumoCombustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField()),
                ('id_categoria_consumo_combustible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='combustible.categoriaconsumocombustible')),
                ('id_tipo_emision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='combustible.tipoemision')),
            ],
        ),
    ]
