# Generated by Django 3.2 on 2023-04-01 21:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('combustible', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumocombustible',
            name='fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
